### ISSUE TITLE
porthole not work

### ISSUE THREAD

**Issue by zhongguo1987** [gnif/Porthole-Guest-Driver#1]
When the QEMU command adds a porthole device, it stays in waiting for connect event through porthole-test.exe 。
   The command to add a porthole device in QEMU is as follows:
        -device porthole,bus=pci.0,chardev=charchannel2,id=channel1 -chardev spiceport,name=org.spice-space.stream.0,id=charchannel2

**Comment by gnif** [comment]
Porthole is an experimental in progress branch, it is incomplete and does not work. Please do not open issues with regards to this branch.
